<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ZPLParser.Demo.WinForms</AssemblyName>
    <RootNamespace>ZPLParser.Demo</RootNamespace>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <StartupObject>ZPLParser.Demo.Program</StartupObject>
    <ApplicationIcon>Diagraph.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup Condition="'$(DesignTimeBuild)' != 'true'">
    <ProjectReference Include="..\Labelparser-ZPL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Diagraph.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Labelparser-ZPL.csproj" />
  </ItemGroup>
</Project>
