<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ZPLParser.Demo.WinForms</AssemblyName>
    <RootNamespace>ZPLParser.Demo</RootNamespace>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <ItemGroup Condition="'$(DesignTimeBuild)' != 'true'">
    <ProjectReference Include="..\Labelparser-ZPL.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(DesignTimeBuild)' == 'true'">
    <Reference Include="Labelparser-ZPL">
      <HintPath>..\bin\Any CPU\Debug\Labelparser-ZPL.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
